# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods --pre
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/Badgeable.xcworkspace -scheme Badgeable-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0'
- pod lib lint
